lsコマンドを作る （l,a,rオプション）
masanarih0ri/ruby-practices pull request #10
Opened 2021-12-12 10:45 UTC by masanarih0ri

## 内容
* lsコマンドの -l, -a, -rオプションを指定して、実際のlsコマンドと同じ動作になるようにしました。

## スクリーンショット

### オプションなし
![image](https://user-images.githubusercontent.com/20497053/145709134-d90a1b88-0533-4991-8787-3b84d99385bd.png)

### -aオプションのみ
![image](https://user-images.githubusercontent.com/20497053/145709159-cdf96e72-4b0f-4a47-a290-e5a252eac644.png)

### -lオプションのみ
![image](https://user-images.githubusercontent.com/20497053/145709175-1488d8be-cb20-40f7-90b5-4dec11e7e8a9.png)

### -rオプションのみ
![image](https://user-images.githubusercontent.com/20497053/145709195-98b7d2b6-d4b2-4ea9-a39f-3e18a1f0d05a.png)

### -alオプション
![image](https://user-images.githubusercontent.com/20497053/145709204-29dd6bfc-0d55-470b-a915-c1266d9a640e.png)

### -alrオプション
![image](https://user-images.githubusercontent.com/20497053/145709221-57f4b148-c140-43b7-a258-87e099cfe949.png)

### -lraオプション（結果は上と同じ）
![image](https://user-images.githubusercontent.com/20497053/145709248-d3457653-d08c-4656-9dcf-afdca3eaeac7.png)

### -arオプション
![image](https://user-images.githubusercontent.com/20497053/145709257-acc41794-4e88-434f-a125-2deea6d74b41.png)

### -alオプション
![image](https://user-images.githubusercontent.com/20497053/145709269-22e8a3ef-67a6-47c1-9599-b0178740528a.png)

### -lrオプション
![image](https://user-images.githubusercontent.com/20497053/145709294-08914e0b-9198-43c1-8533-97818248656f.png)

2021-12-12 15:50 UTC, u1tnk requested changes
メソッド名と、フォーマット処理がまとまってないところが気になりましたので整理してみましょう 💪

2021-12-12 15:50 UTC, u1tnk commented on 05.ls/ls_final.rb
> +  column_count = 3.0
固定の値として使うのであれば定数の方が良いですね。
defの上に `COLUMN_COUNT` として定義しましょう。
この場合変更も無いので、`calc_file_count_per_column` のところで定義して引数からは消しても良いですね。

2021-12-12 15:50 UTC, u1tnk commented on 05.ls/ls_final.rb
> +def parse_input(command_options, target_files)
このメソッドの名前が parse_inputなのですが、中身は file情報を収集していそうなので修正しましょう。

2021-12-12 15:50 UTC, u1tnk commented on 05.ls/ls_final.rb
> +  file_count_per_column = calc_file_count_per_column(current_directory_files, column_count)
column_countもそうですが、これは `l`オプションが無いとき専用の処理だと思います。

メイン処理が直接呼ぶのは大きな処理の流れだけにした方が流れが分かりやすくなるので、ここにこの処理があるのは良くないです。

2021-12-12 15:50 UTC, u1tnk commented on 05.ls/ls_final.rb
> +  option_l, parsed_files = parse_input(command_options, current_directory_files)
option_lは command_options変数を見れば良いので、一回引数に渡して返り値で取る必要は無いと思います。

2021-12-12 15:50 UTC, u1tnk commented on 05.ls/ls_final.rb
> +    format_other_option(divided_files, file_count_per_column)
lオプションの有無で、他のオプションがあるときでは無いはずです。

long/shortとかオプションの有無で選択されたフォーマットに名称を付けた方が良いですね。

2021-12-12 15:50 UTC, u1tnk commented on 05.ls/ls_final.rb
> +  if option_l
option_lを各所で見ていますが、formatするとき一回見るだけで良いはずです。

2021-12-12 15:50 UTC, u1tnk commented on 05.ls/ls_final.rb
> +def format_files(option_l, divided_files, file_count_per_column)
formatは 単純なデータをある形式の文字列にすることです。
format_filesという名前であればformatの全体処理をしそうなので、divide_filesなどはこの中、option_lの判断をした後に呼ぶものだと思います。

2021-12-14 00:20 UTC, masanarih0ri commented on 05.ls/ls_final.rb
> +def parse_input(command_options, target_files)
こちら変更しました。

2021-12-14 00:20 UTC, masanarih0ri commented on 05.ls/ls_final.rb
> +    format_other_option(divided_files, file_count_per_column)
こちらも変更してみましたがどうでしょうか？？

2021-12-14 00:48 UTC, masanarih0ri commented on 05.ls/ls_final.rb
> +def format_files(option_l, divided_files, file_count_per_column)
引数にdivided_filesを渡すのではなく、中で計算してからメソッド内で渡す形にして、divide_filesというメソッド定義を無くしました。

2021-12-14 00:48 UTC, masanarih0ri commented on 05.ls/ls_final.rb
> +  column_count = 3.0
こちら変更しました！

2021-12-14 00:51 UTC, masanarih0ri commented on 05.ls/ls_final.rb
> +  file_count_per_column = calc_file_count_per_column(current_directory_files, column_count)
こちらは別のメソッドの中に入れるようにしました。

2021-12-14 00:53 UTC, masanarih0ri commented on 05.ls/ls_final.rb
> +  if option_l
ひとまずdivide_filesは消したので、そこでoption_lを見ることは無くなりました。

2021-12-14 01:13 UTC, masanarih0ri commented on 05.ls/ls_final.rb
> +  option_l, parsed_files = parse_input(command_options, current_directory_files)
command_optionsがメイン関数の中に入っていないときに上記の書き方をしていたのですが、メイン関数の中にあるのでcommand_optionsを参照すれば良いですね…。修正しました！

2021-12-14 08:13 UTC, u1tnk requested changes

2021-12-14 08:13 UTC, u1tnk commented on 05.ls/ls_final.rb
> +  formatted_files = format_files(command_options, collected_files, current_directory_files)
current_directory_filesは file_nameの配列で、 collected_filesには nameが入っているので、collectd_filesに含まれている状態なので、それ以降渡す必要は無いと思います。

2021-12-14 08:13 UTC, u1tnk commented on 05.ls/ls_final.rb
> +    file_details = []
この配列にフラットに全ての情報が入れて、後で一行の数分sliceして使うというのは分かりにくいです。
まず、二重の配列、以下のようにした方が良いです。中身はイメージです。

```
[
  [hoge_file_name,1,...  ],
  [fuga_file_name , 2]
]
```

ただ、これも内部的な配列の順番を覚えないと目的のデータが取り出せなくて使いづらいですね。
そういうときはhashを使います。

```
[
  {
    name:  hoge,
    mode: 1,
  }
....
]
```

このように各ファイルごとにhashを作って file_dtailsに追加していけば使いやすくなると思います。

2021-12-14 23:59 UTC, masanarih0ri commented on 05.ls/ls_final.rb
> +  formatted_files = format_files(command_options, collected_files, current_directory_files)
こちらなんですが、format_filesの引数から消せるのは理解できたのですが、output_filesの引数からどう消せばいいのかのイメージがつきませんでした。
引数に渡している formatted_files から `"README.md        "` のような文字列は取れるので、無理矢理やればできそうですが、処理が冗長になってしまう気がしたので、output_filesの方には残すようにしました。

2021-12-15 14:52 UTC, masanarih0ri commented on 05.ls/ls_final.rb
> +    file_details = []
hashを作って処理する方法で対応しました！👍

2021-12-16 00:58 UTC, u1tnk commented on 05.ls/ls_final.rb
> +  formatted_files = format_files(command_options, collected_files, current_directory_files)
なるほど、formatted_filesが中間形式になって元の名前が消えてしまってるんですね。

いくつか対処方法はありますが、outputとformat処理を一緒にするのが簡単そうに見えます。

2021-12-16 01:01 UTC, u1tnk requested changes

2021-12-16 01:01 UTC, u1tnk commented on 05.ls/ls_final.rb
> +  if command_options['l']
Lオプションを見るのは一回で良いと指摘したと思いますのでここでは不要です。

`file_details.map{_1["file_name"]}` でtarget_files相当にすぐ戻りますし。

2021-12-17 01:25 UTC, masanarih0ri commented on 05.ls/ls_final.rb
> +  formatted_files = format_files(command_options, collected_files, current_directory_files)
outputとformatを同じ処理に移してcurrent_directory_filesは1回しか引数で渡さないようにしました。

2021-12-17 02:08 UTC, u1tnk approved these changes

2021-12-17 14:14 UTC, merged