lsコマンドを作成する（オプションなし）
masanarih0ri/ruby-practices pull request #4
Opened 2021-11-06 14:02 UTC by masanarih0ri

## 内容
* lsコマンドと同じ動作をするようにRubyプログラムを書きました
* 現在いるディレクトリのファイルなどが3列になって表示されます
* 表示については以下の数字の順番になります（10個の場合）

```
1  5  9
2  6  10
3  7
4  9
```

## スクリーンショット
![image](https://user-images.githubusercontent.com/20497053/140612387-de41c85b-965c-4c0f-9b92-62416bc56708.png)

## 日本語対応について
何もしていないのですが、ああああ.txtというファイル名が問題なく表示されていました。バグやエラーではないのでそのままですが、レビューに加えてそのあたりの理由を教えていただけると幸いです。

2021-11-11 01:36 UTC, u1tnk requested changes
行列を入れ替えて表示するところ頑張ってますね。
ナイスチャレンジ 👍 だし、とても勉強になったと思います。

ただ、rubyには以下の便利メソッドがあるのでこれを使えば短くなると思うので、使ってみてください。
https://docs.ruby-lang.org/ja/latest/method/Array/i/transpose.html

ls2以降で色々複雑になるので、いったんできるだけシンプルにしましょう。

2021-11-11 01:36 UTC, u1tnk commented on 05.ls/ls.rb
> +  file_count_per_column = calc_file_count_per_column(CURRENT_DIRECTORY_FILES, COLUMN_COUNT)
定数で定義しているものを引数に入れなくても良いと思いますがどうでしょうか。

2021-11-11 01:36 UTC, u1tnk commented on 05.ls/ls.rb
> +CURRENT_DIRECTORY_FILES = Dir.glob('*')
実行時に動的に取得する値なので定数では無く変数に入れましょう。

2021-11-15 13:57 UTC, masanarih0ri commented on 05.ls/ls.rb
> +  file_count_per_column = calc_file_count_per_column(CURRENT_DIRECTORY_FILES, COLUMN_COUNT)
こちらは定数ではなく、関数内部の変数にすることにしました。

2021-11-15 13:57 UTC, masanarih0ri commented on 05.ls/ls.rb
> +CURRENT_DIRECTORY_FILES = Dir.glob('*')
メソッド内で呼び出す変数を使うようにしました。

2021-11-15 14:03 UTC, masanarih0ri commented
コメントいただいた箇所の修正をしました！
transposeを使って数行コードが短くなったので、再度ご確認をお願いします！

2021-11-16 02:01 UTC, u1tnk requested changes

2021-11-16 02:01 UTC, u1tnk commented on 05.ls/ls.rb
> +  last_column = adjusted_file_list.last
ここはもっと短くできますね。
each_sliceして配列を分割する前に 3の倍数になるように配列の数を調節するとかどうでしょうか。

2021-11-17 13:21 UTC, masanarih0ri commented on 05.ls/ls.rb
> +  current_directory_files.each_slice(file_count_per_column) { |file| devided_file_list << file }
なるほど、Enumerableオブジェクトを Arrayに変換すれば良いのですね。修正しました！

2021-11-17 13:22 UTC, masanarih0ri commented on 05.ls/ls.rb
> +  devided_file_list = []
こちら修正しました！

2021-11-17 13:33 UTC, masanarih0ri commented on 05.ls/ls.rb
> +  last_column = adjusted_file_list.last
`empty_column_data_size.times { last_column << '' }` のようにして1行で書くようにしました！

2021-11-19 07:52 UTC, u1tnk requested changes

2021-11-19 07:52 UTC, u1tnk commented on 05.ls/ls.rb
> +  last_column = adjusted_file_list.last
`(file_count_per_column - last_column.size).times ...`
とすれば0回のときは実行されないので if文もいらないですよ。

2021-11-19 12:02 UTC, masanarih0ri commented
@u1tnk 
レビューありがとうございます！確かにif文要らないですね〜。`0.times` とできるの知りませんでした。修正しました！

2021-11-20 01:58 UTC, u1tnk approved these changes

2021-11-22 00:38 UTC, merged