lsコマンドを作る （-l オプション）
masanarih0ri/ruby-practices pull request #9
Opened 2021-11-28 00:28 UTC by masanarih0ri

## 内容
ls -l のコマンドをRubyで動作するように作成しました。
* ファイル権限、リンク数、ユーザー、グループ、ファイルサイズ、最終更新の時刻、ファイル名を表示します。
* 余白はリンク数、ファイルサイズ、最終更新の時刻が右揃え、そのほかは左揃えです。

## スクリーンショット

2021-11-29 02:04 UTC, u1tnk requested changes

2021-11-29 02:04 UTC, u1tnk commented on 05.ls/ls_with_l.rb
> +  display_l_option_files
display_xxx という名前のメソッドが実質メイン処理になってますね。

情報収集、整理と分けて、格機能の 入出力を意識すると分かりやすくなりますね。

https://u1tnk.github.io/blog/2020/12/17/structured_programming/

こちらの私のブログが参考になると思います。

2021-12-04 14:33 UTC, masanarih0ri commented on 05.ls/ls_with_l.rb
> +  adjusted_file_details.transpose
なるほど。配列をtransponseして一時的に情報単位での配列を作って文字列の長さを調整し、再度transposeで1つのファイル単位に戻すという形で実装しましたがいかがでしょうか？

2021-12-04 14:34 UTC, masanarih0ri commented on 05.ls/ls_with_l.rb
> +    file_mode = file_mode[0] == '1' ? file_mode : "0#{file_mode}"
sprintfだとrubocopに怒られてしまったので、formatを使って修正しました。

2021-12-04 14:35 UTC, masanarih0ri commented on 05.ls/ls_with_l.rb
> +  display_details_count = 7
こちらは定数に切り出しました。

2021-12-04 14:35 UTC, masanarih0ri commented on 05.ls/ls_with_l.rb
> +  display_l_option_files
display_xxxという名前ではなく、output_filesという命名にしました。他の部分も少し命名を変えています。

2021-12-05 13:49 UTC, u1tnk requested changes

2021-12-05 13:49 UTC, u1tnk commented on 05.ls/ls_with_l.rb
> +if l_option?
l_optionがあっても無くても、表示する事自体は変わらず、出力するフォーマットが違うだけなので、メソッド名が output_filesとdisplay_filesで分かれているのはおかしいです。

また、ここがメイン処理の始めになると思うのですが、これだといきなりoutputで終わってしまっていて処理の流れが分かりません。
主な処理ごとに入出力を整理しましょう。

情報収集処理の結果を出力する処理に渡す…というようにしましょう。

[失なわれた構造化プログラミング、そしてオブジェクト指向へ…](https://u1tnk.github.io/blog/2020/12/17/structured_programming/)

こちらの私のブログが参考になると思います 💪

2021-12-12 01:48 UTC, merged